// <auto-generated>
// Generated by build.sh — run build.sh to replace with real compiled SPIR-V.
// </auto-generated>
namespace BeamQuest.Rendering
{
    internal static class ShaderBytecode
    {
        // Populated by build.sh after glslc compiles shaders/*.vert and shaders/*.frag.
        // Placeholders are empty arrays; WorldRenderer.LoadSpirV falls back to disk files
        // when the embedded bytes are empty (development-time sideload via adb push).
        public static readonly byte[] world_vert = [];
        public static readonly byte[] world_frag = [];
        public static readonly byte[] ui_vert    = [];
        public static readonly byte[] ui_frag    = [];
    }
}
